### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by noejunior792** [IgorSemed0/IgorSemed0#1]
The contact links on WhatsApp, Instagram and Gmail are not from the account owner and this can be bad for people who want to keep in touch with you.

In addition, the introduction is about a person named Manuel Horácio and not Igor Semedo, and the link to the Manuel Art project is giving a 404 error.

**Comment by IgorSemed0** [comment]
Thanks a lot for the Issue. I'm closing it now. 
Already reviewed.
